name: 'Reusable Build and Analyze'

on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: string
      commit_hash:
        required: true
        type: string
      project_version:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_ORGANIZATION:
        required: true

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Commit ${{ inputs.commit_hash }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash }}
          fetch-depth: 0 # Fetch all history for all tags and branches
          clean: true

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v4
        with:
          java-version: '11' # Adjust to your project's required Java version
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Attempt to Build Project'
        id: build
        # Use 'continue-on-error' to ensure the workflow doesn't stop if the build fails.
        # We will check the outcome in the next step.
        continue-on-error: true
        run: mvn -B clean install -DskipTests

      - name: 'Run SonarCloud Scan (if build succeeded)'
        # This step only runs if the previous 'build' step was successful.
        if: steps.build.outcome == 'success'
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=maven-issue-${{ inputs.issue_number }} \
            -Dsonar.projectName="Maven Issue #${{ inputs.issue_number }}" \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectVersion=${{ inputs.project_version }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.newCode.referenceBranch=1.0 # Set leak period for comparison

      - name: 'Handle Build Failure'
        # This step only runs if the 'build' step failed.
        if: steps.build.outcome != 'success'
        run: |
          echo "::warning::Build failed for commit ${{ inputs.commit_hash }}. Skipping SonarCloud analysis for this version."
